# Generated by Django 4.2.16 on 2024-10-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
