# Generated by Django 4.2.16 on 2024-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_user_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nativeLanguage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
