# Generated by Django 4.2.16 on 2025-02-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.CharField(default='media/profile_images/MainAfter.jpg', max_length=255),
        ),
    ]
