# Generated by Django 4.2.16 on 2025-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_alter_profile_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.CharField(default='profile_images/MainAfter.jpg', max_length=255),
        ),
    ]
