# Generated by Django 5.2.5 on 2025-10-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_profile_age_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
