# Generated by Django 5.2.7 on 2025-10-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0011_remove_profile_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
    ]
